// function playRoundGame (playerSelection, computerSelection){




// }

// function computerPlay (playerSelection, computerSelection){

// }

console.log(getRandomInt(3));



//This function will generate a random number between 0 and 2 if passed the parameter 3.  
//This gives us three choices, to randomly have the computer select rock, paper, or scissors.
function getRandomInt(max) {

    let Random_Number_Btwn_Zero_and_One = Math.random();
    console.log(Random_Number_Btwn_Zero_and_One);

    let MaxNumber = max * Random_Number_Btwn_Zero_and_One;
    console.log(MaxNumber);

    //Math.floor effectively truncates the decimal from whatever the float values is.  i.e - 2.6 becomes 2.
    let RandomNumberforComputer = Math.floor(MaxNumber);  
    console.log("The Random Number generated by the function is " + RandomNumberforComputer);

    return RandomNumberforComputer
    
}

function ComputerChooses(num) {

    


}



//test code here

// const playerSelection = "rock";
// const computerSelection = computerPlay();
// console.log(playRound(playerSelection, computerSelection));